config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('contact/', include('contact.urls')),
]

contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    path('/contact', views.contact, name='contact'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

contact/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

contact/views.py
from django.shortcuts import render

# Create your views here.


def contact(request):
    return render(request, 'contact/contact.html')

home/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home/home.html')

contact/templates/contact/contact.html
{% extends 'base.html' %}

{% block title  %}Contact{% endblock %}

{% block content %}
<h1> THIS IS A CONTACT PAGE🐳</h1>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>THIS IS A HOME PAGE 👻</h1>
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Alegrosz - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}" async defer></script>
</head>
<body>
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}" async defer></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static '/logo.svg' %}" alt="" width="30" height="24"
                 class="d-inline-block align-text-top">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=" {% url 'contact:contact' %} ">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{# {% url 'product:product_list' %} #}">Products</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container mt-5">
    <div class="row">
        <div class="col">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

</body>
</html>